# Generated by Django 3.1 on 2022-01-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220102_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category',), 'verbose_name_plural': 'categoris'},
        ),
    ]
